
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author OLA
 */
public class LecturalCourses extends javax.swing.JFrame {

    DbConnect dbcon = new DbConnect();
    int h_id;
    Vector<Integer> lecturalcourse_id = new Vector<Integer>();

    /**
     * Creates new form LECTURERS_COURSES
     */
    public LecturalCourses() {
        initComponents();
        fetch();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 0, 102));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 255));
        jLabel1.setText(" LECTURER'S COURSE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 220, 38));

        jLabel2.setBackground(new java.awt.Color(102, 102, 0));
        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setText("List of lecturers");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, 20));

        jLabel3.setBackground(new java.awt.Color(102, 102, 0));
        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setText("List of courses");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, 20));

        jLabel4.setBackground(new java.awt.Color(204, 153, 0));
        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setText("Lecturere's courses");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 150, 20));

        jPanel2.setBackground(new java.awt.Color(153, 0, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { " ", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 520));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 270, 540));

        jPanel3.setBackground(new java.awt.Color(153, 0, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setViewportView(jList2);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 490));

        jButton4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton4.setText("Assign Course");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 130, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 280, 540));

        jPanel4.setBackground(new java.awt.Color(153, 0, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList3);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 490));

        jButton3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton3.setText("Remove");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 118, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 130, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 290, 540));

        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 860, 40));

        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 860, 560));

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 650, 118, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        delete();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        save();

// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (jComboBox1.isFocusOwner() && jComboBox1.getSelectedIndex() > 0) {
            filterCombo();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LecturalCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LecturalCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LecturalCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LecturalCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LecturalCourses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

    private void fetchCombo() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.addElement("-- Select Depertment --");
        try {
            String query = "select name from department where status=0";

            dbcon.rs = dbcon.st.executeQuery(query);
            while (dbcon.rs.next()) {
                model.addElement(dbcon.rs.getString(1));

            }
            // jComboBox1.setModel(model);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "An Error Occur while fetching information from database");
            ex.printStackTrace();
        }
    }

    private void fetch() {
        DefaultListModel model = new DefaultListModel();
        DefaultListModel model1 = new DefaultListModel();
        DefaultListModel model2 = new DefaultListModel();
        DefaultComboBoxModel model3 = new DefaultComboBoxModel();
        lecturalcourse_id = new Vector<Integer>();
        model.addElement("-- LECTURALS --");
        model1.addElement("-- COURSES --");
        model2.addElement("-- COURSE LECTURAL --");
        model3.addElement("-- FILTER --");
        model3.addElement("All");
        try {
            String query = "select id,code from course where status=0";
            dbcon.rs = dbcon.st.executeQuery(query);
            while (dbcon.rs.next()) {
                model1.addElement(dbcon.rs.getString("code"));

            }
            query = "select id,name,code from lectural where status=0";
            dbcon.rs = dbcon.st.executeQuery(query);
            while (dbcon.rs.next()) {
                model.addElement(dbcon.rs.getString("name") + ": " + dbcon.rs.getString("code"));
                model3.addElement(dbcon.rs.getString("name"));

            }
            query = "select id,lectural,course from lectural_course where status=0";
            dbcon.rs = dbcon.st.executeQuery(query);
            while (dbcon.rs.next()) {
                model2.addElement(dbcon.rs.getString("course") + ": " + dbcon.rs.getString("lectural"));
                lecturalcourse_id.addElement(dbcon.rs.getInt("id"));
            }
            jList1.setModel(model);
            jList2.setModel(model1);
            jList3.setModel(model2);
            jComboBox1.setModel(model3);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "An Error Occur while fetching information from database");
            ex.printStackTrace();
        }

    }

    private void save() {
        if (jList1.getSelectedIndex() < 1 && jList2.getSelectedIndex() < 1) {
            JOptionPane.showMessageDialog(rootPane, "You must select both lectural and course");
            return;
        }

        String name = jList1.getSelectedValue().toString();
        String code = jList2.getSelectedValue().toString();
        try {
            String query = "insert into lectural_course (lectural,course) values(?,?)";
            dbcon.ps = dbcon.con.prepareStatement(query);
            dbcon.ps.setString(1, name);
            dbcon.ps.setString(2, code);
            if (dbcon.ps.executeUpdate() == 1) {
                JOptionPane.showMessageDialog(rootPane, "Information Saved Successfully");
                fetch();
                clear();
            } else {
                JOptionPane.showMessageDialog(rootPane, "An Error Occur, Your information is not save");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "An Error Occur, Your information is not save");
            e.printStackTrace();
        }
    }

    private void delete() {
        if (jList3.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(rootPane, "Please select a feild to be deleted");
            return;
        }
        int id = lecturalcourse_id.elementAt(jList3.getSelectedIndex() - 1);
        try {
            String query = "delete from lectural_course where id=" + id;
            dbcon.ps = dbcon.con.prepareStatement(query);
            if (dbcon.ps.executeUpdate() == 1) {
                JOptionPane.showMessageDialog(rootPane, "Information Deleted Successfully");
                fetch();
                clear();
            } else {
                JOptionPane.showMessageDialog(rootPane, "An Error Occur, Your information is affected");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void clear() {
        jList1.clearSelection();
        jList2.clearSelection();
        jList3.clearSelection();
    }

    private void filterCombo() {
        DefaultListModel model2 = new DefaultListModel();
        lecturalcourse_id = new Vector<Integer>();
        model2.addElement("-- COURSE LECTURAL --");
        try {

            String query = "select id,lectural,course from lectural_course where status=0 and lectural like '%" + jComboBox1.getSelectedItem().toString() + "%'";
            if (jComboBox1.getSelectedIndex() == 1) {
                query = "select id,lectural,course from lectural_course where status=0";
            }
            dbcon.rs = dbcon.st.executeQuery(query);
            while (dbcon.rs.next()) {
                model2.addElement(dbcon.rs.getString("course") + ": " + dbcon.rs.getString("lectural"));
                lecturalcourse_id.addElement(dbcon.rs.getInt("id"));
            }
            jList3.setModel(model2);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "An Error Occur while fetching information from database");
            ex.printStackTrace();
        }
    }
}
